name: apphud
description: Official Apphud Flutter SDK is a lightweight open-source library to manage auto-renewable subscriptions and other in-app purchases in your iOS/Android app. No backend required.
version: 2.2.5
homepage: 'https://apphud.com'
repository: 'https://github.com/apphud/ApphudSDK-Flutter'

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.1.0
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  json_serializable: ^5.0.2
  pedantic: ^1.11.1

flutter:
  plugin:
    platforms:
      android:
        package: com.apphud.fluttersdk
        pluginClass: ApphudPlugin
      ios:
        pluginClass: ApphudPlugin
